# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ted's Cloud Infrastructure Blog
email: theodorejmartin@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello, my name is Ted Martin. I have decided to create this blog in order to educate other likeminded individuals that use technology,
  particularly Cloud Based. Microsoft Azure is my go to Public Cloud provider, and I plan on covering Microsoft Azure heavily.
github_username: tedmartn
linkedin_username: ted-martin-bb61418b
minimal_mistakes_skin: air
search: true


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Ted Martin"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Cloud Architect, Microsoft Azure & Microsoft 365."
  location: "Davenport, IA"
  email: theodorejmartin@outlook.com
  links:
      - label: "LinkedIn"
        icon: "fab fa-fw fa-linkedin-in"
        url: "https://www.linkedin.com/in/ted-martin-bb61418b/"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/tedmartn"
footer:
  links:
      - label: "LinkedIn"
        icon: "fab fa-fw fa-linkedin-in"
        url: "https://www.linkedin.com/in/ted-martin-bb61418b/"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/tedmartn"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid  
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
